image: registry.brickabode.com/dotnetinpostgresql/pldotnet

stages:
    - test

installcheck:
    stage: test
    script:
        - /etc/init.d/postgresql restart
        - make && make plnet-install && make installcheck
    after_script:
        - cat regression.diffs || true

